gate_pkl_file: "objects_IDs/base_gate_IRL.pickle"
gsplat_path: "../outputs/right/splatfacto/2025-05-09_151825"
load_checkpoint: "step-000039999.ckpt"
to_save_checkpoint: "step-000040004.ckpt"
gate_poses:
  - [0.0, -2.0, -0.2, -1.57, 0.0, 0.0]
  - [-0.402, -3.5, -0.2, -2.093, 0.0, 0.0]
  - [-1.5, -4.598, -0.2, -2.616, 0.0, 0.0]
  - [-3.0, -5.0, -0.2, -3.14, 0.0, 0.0]

